services:
  # Base de Datos (MySQL)
  mysql-db:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}      # Docker busca esto en tu .env
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  # Contenedor de la Aplicación (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    networks:
      - laravel-network
    depends_on:
      - mysql-db # Espera a que la BBDD esté lista

  # Servidor Web (Nginx)
  webserver:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - laravel-network
    depends_on:
      - app

  # Worker de Laravel (Manejo de Colas)
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue-worker
    restart: unless-stopped
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    networks:
      - laravel-network
    depends_on:
      - app
      - mysql-db # Espera a la app y a la BBDD

# Redes para comunicar los contenedores entre sí
networks:
  laravel-network:
    driver: bridge

# Volumen persistente para que no se borre la bbdd
volumes:
  mysql-data:
    driver: local